### ISSUE TITLE
Modification System Notifications - Update System to Check User's Existing Project Subscription & Respond Appropriately

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#219]
# General Instruction

Please update the system to **perform a check on a user's existing modification request subscriptions each time a user is added to a project**.
## Triggers

**TRIGGERS - Users may be added to a project using one of two methods - the new check should be implemented for both methods**:
1. **Method1 - via admin menu** ![image](https://cloud.githubusercontent.com/assets/4098544/8657312/eb939dcc-296a-11e5-83dc-521fe3fbea97.png)
2.  **Method 2 - via Project Details - Stakeholders subtab** ![image](https://cloud.githubusercontent.com/assets/4098544/8657413/6bbaf392-296b-11e5-8be6-5de34229825b.png)
## Check & Response

**CHECK & RESPONSE**:
1. The system should **query/check to see the users existing subscription participation for  _ALL PROJECTS_ for both modification subscription checkbox option** (shown below).
2. The system should be updated to **add the user to the new project with an identical checkbox configuration as _ALL PROJECTS_** - meaning that **if the user participates (is selected) for _ALL PROJECTS_, then the user account should inherit that same participation for the newly associated project**. Conversely, **when either checkbox is unselected, the user account should likewise inherit that same unselected configuration** for the newly associated project.
![image](https://cloud.githubusercontent.com/assets/4098544/8657593/89a74076-296c-11e5-8694-91ca5d1f5ab2.png)

**Comment by kanglu666** [comment]
done at SHA staging, ready for testing

**Comment by slmessier** [comment]
functionality has been tested and confirmed by Scott in STAGING environment. 

I will open up to Tad for confirmation and if successfully confirm coordinate push to PRODUCTION.

**Comment by Tad-Daniel** [comment]
Seem to be working in stagging.  Lets push to production ASAP.  Thanks

**Comment by Tad-Daniel** [comment]
The issue partly remains.  The system appears to work correctly when creating a new modification request but the contact list is not maintained for responses to that modification.  When a user has been included in a notification they should also receive all subsequent responses.

**Comment by Tad-Daniel** [comment]
Has this fix been implemented?  It still persists in production.

**Comment by slmessier** [comment]
Hi Viji - **please utilize the comment threads associated with this issue to familiarize yourself with the expected workflow, and then begin investigation the source of the issue reported by Tad** 

> The issue partly remains. The system appears to work correctly when creating a new modification request but **_the contact list is not maintained for responses to that modification. When a user has been included in a notification they should also receive all subsequent responses._**

My guess is that the workflow within existing code may not align completely as designed and requires additional logic be developed to do so. With that in mind please be certain that you are clear on the designed workflow using the specifications outlined above, and **contact me for support if there are
Identify any additional questions there is material that you would like to clarify.**

**Comment by Tad-Daniel** [comment]
The issue remains in production and if possible I would like for it to be a priority at this time.

**Comment by slmessier** [comment]
@Tad-Daniel  - Is this issue from July 2016 still valid or has it become obsolete and could be closed at this time? Please research and advise when you have an opportunity. Otherwise not time-sensitive. Thank you!

**Comment by Tad-Daniel** [comment]
I believe we have now resolved this issue.
