### ISSUE TITLE
QA Toolkit - Implement Processing Indicator Visualization during System Processing & PDF Generation

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#344]
**Develop a visual indicator that system is working to respond to a user’s click.**

**Required Enhancement Specification(s):** 
1. An explicit indication that appears for the full duration that the system is in a processing stage
2. Previously recorded GitHub #44 (related)

**Optional Specifications (if feasible as per discretion):**
1. Implementation for cases beyond PDF ‘Print Functions’ (if suitable)
2. Status or Time of Processing Progress
3. Enforcement of User Control during Processing Stage 

_Tracking Note: this issue was originally requested as **No. 14.A within the Task 14 Scope of Work Agreement**, and as referenced within GH issue #343 of this repository._

**Comment by Tad-Daniel** [comment]
I have some thoughts on this item.   If I had to show what I was thinking of it would be something like this.  a spinning progress indicator in the screen center to clearly get the user attention.

I like the progress bar at the top of the github pages but we need something to really catch user attention as many of them have very limited database experience.

**Comment by Tad-Daniel** [comment]
reopened. clicked wrong button

**Comment by vijme** [comment]
Implemented in dev. Processing bar will be visible on all button click for all toolkits. Involved significant code change with regard to the "PRINT" functionality. So please test button clicks and prints thoroughly. Let me know if you need changes.

**Comment by HollySchuelerKCI** [comment]
It appears that the progress indicator does not appear when the user clicks the save button when entering information on the Project Details page. This occurs when the user is adding a new project and clicking save when updating the tabs at the bottom of the Project Details page. Below are the steps to replicate:

- Projects Tab
- Add New Project button
- Enter new project information
- Click Save

![image](https://user-images.githubusercontent.com/25441512/30489712-f88c4b24-9a05-11e7-961e-1452e63144d1.png)

![image](https://user-images.githubusercontent.com/25441512/30490378-c422c186-9a07-11e7-8fec-5f739cf4f308.png)


In addition, the system does not display the progress indicator when editing on the Inspections QA2 tab. Below are the steps to replicate:

- Inspections -> QA2
- Edit Project button
- Enter new information
- Click Save
![image](https://user-images.githubusercontent.com/25441512/30490169-3363ba7e-9a07-11e7-9e69-d866cb8bbdcf.png)

**Comment by HollySchuelerKCI** [comment]
It appears that the progress indicator does not appear when the user clicks the close button when adding a comment to a project.

- Projects -> Projects List
- Comment button
- Enter Comment
- Close

![image](https://user-images.githubusercontent.com/25441512/30490047-df391084-9a06-11e7-86a3-e800af098d4b.png)

**Comment by vijme** [comment]
Issues fixed in dev

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Development Environment.

**Comment by HollySchuelerKCI** [comment]
This issue has been successfully validated by the project team in the Staging Environment.

**Comment by Tad-Daniel** [comment]
Looks god and we can include this in the update but this may need some tweaking.  It still does not stop someone from tapping a button more than once therby allowing duplicate submissions.

**Comment by Tad-Daniel** [comment]
This system looks good but I want to watch it for a while to be completely sure.

**Comment by Tad-Daniel** [comment]
I believe this is working correctly
